[versions]
compileSdk = "31"
targetSdk = "31"

compileSdkTiramisu = "33"
targetSdkTiramisu = "33"

minSdk = "23"
retrofit = "2.9.0"
roomVersion = "2.4.2"
nav_version = "2.5.0-alpha03"
connect = "0.12.3"
particle_network_version = "0.12.6"
particle_network_code = "22"

[libraries]
#official
core-ktx = "androidx.core:core-ktx:1.7.0"
appcompat = "androidx.appcompat:appcompat:1.4.1"
material = "com.google.android.material:material:1.5.0"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"
livedata = "androidx.lifecycle:lifecycle-livedata-ktx:2.4.0"
viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1"
annotation = "androidx.annotation:annotation:1.3.0"
activity-ktx = "androidx.activity:activity-ktx:1.4.0"
fragment-ktx = "androidx.fragment:fragment-ktx:1.4.1"

lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0"

#libs
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

connect-common = { module = "network.particle:connect-common", version.ref = "connect" }
connect = { module = "network.particle:connect", version.ref = "connect" }
connect-evm-adapter = { module = "network.particle:connect-evm-adapter", version.ref = "connect" }
connect-sol-adapter = { module = "network.particle:connect-solana-adapter", version.ref = "connect" }
connect-phantom-adapter = { module = "network.particle:connect-phantom-adapter", version.ref = "connect" }
connect-wallet-connect-adapter = { module = "network.particle:connect-wallet-connect-adapter", version.ref = "connect" }

lifecycle-viewmodel-ktx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"
okhttp3-logging-interceptor = "com.squareup.okhttp3:logging-interceptor:4.9.3"
rxandroid = "io.reactivex.rxjava3:rxandroid:3.0.0"
rxjava = "io.reactivex.rxjava3:rxjava:3.0.0"
okhttp3 = "com.squareup.okhttp3:okhttp:4.10.0"

kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0"
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0"

coil = "io.coil-kt:coil:2.0.0-rc03"
coil-svg = "io.coil-kt:coil-svg:2.0.0-rc03"
coil-gif = "io.coil-kt:coil-gif:2.0.0-rc03"

java-websocket = "org.java-websocket:Java-WebSocket:1.5.2"
eddsa = "net.i2p.crypto:eddsa:0.3.0"
bitcoinj = "com.github.bitcoinj:bitcoinj:0.15.10"
timber = "com.jakewharton.timber:timber:4.6.0"
xx-permissions = "com.github.getActivity:XXPermissions:13.5"
gltfio-android = "com.google.android.filament:gltfio-android-lite:1.23.1"
filament-android = "com.google.android.filament:filamat-android-lite:1.23.1"
filament-utils-android = "com.google.android.filament:filament-utils-android-lite:1.20.5"
streamsupport-cfuture = "net.sourceforge.streamsupport:streamsupport-cfuture:1.7.4"

refresh-layout = "io.github.scwang90:refresh-layout-kernel:2.0.5"
refresh-header-material = "io.github.scwang90:refresh-header-material:2.0.5"
zxing-barcodescanner = "com.github.bingoogolapple.BGAQRCode-Android:zxing:1.3.8"
biometric = "androidx.biometric:biometric:1.2.0-alpha04"
magic-indicator = "com.github.hackware1993:MagicIndicator:1.7.0"
utilcodex = "com.blankj:utilcodex:1.31.0"
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
room-test = { module = "androidx.room:room-testing", version.ref = "roomVersion" }

paging = "androidx.paging:paging-runtime:3.1.1"
room-paging = "androidx.room:room-paging:2.5.0-alpha01"
paging-test = "androidx.paging:paging-common:3.1.1"
browser = "androidx.browser:browser:1.3.0"
browser-alpha = "androidx.browser:browser:1.5.0-alpha01"
spinkit = "com.github.ybq:Android-SpinKit:1.4.0"
circle-progress = "com.github.xxhong:CircleProgressKt:2.1.1"
float-menu = "com.github.xxhong:FloatMenu:0.0.1"
toasty = "com.github.xxhong:Toasty:2.1.0"
skeleton = "com.github.xxhong:Skeleton:2.0.3"
collectspkg = 'com.github.xxhong:CollectsPkg:0.8.5'
gson = "com.google.code.gson:gson:2.9.0"
pictureselector = "io.github.lucksiege:pictureselector:v3.10.5"
eventbus = "org.greenrobot:eventbus:3.3.1"
commons-codec = "commons-codec:commons-codec:1.15"
kotson = "com.github.salomonbrys.kotson:kotson:2.5.0"
recyclerview-adapter = "com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.7"
immersionbar = "com.geyifeng.immersionbar:immersionbar:3.2.2"
bannerviewpager = "com.github.zhpanvip:bannerviewpager:3.5.6"
#test
junit = "junit:junit:4.13.2"
junit-ext = "androidx.test.ext:junit:1.1.3"
espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "nav_version" }
[bundles]
retrofit = ["retrofit", "retrofit-converter-gson", "retrofit-converter-moshi"]

[plugins]
jmh = { id = "me.champeau.jmh", version = "0.6.5" }